name: Add maintenance issue to Project

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    if: github.event.label.name == '保守運用'
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Add issue to GitHub Project and set Estimate
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_PAT }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          OWNER: ${{ secrets.OWNER_PROJECT_ID }}
          ESTIMATE: 1
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          echo "Adding issue $ISSUE_URL to project $PROJECT_ID"

          ITEM_JSON=$(gh project item-add $PROJECT_ID --url $ISSUE_URL --owner $OWNER --format json)
          
          ITEM_ID=$(echo "$ITEM_JSON" | jq -r '.id')

          echo "Setting Estimate=$ESTIMATE on item $ITEM_ID"
          gh project item-edit "$PROJECT_ID" --id "$ITEM_ID" --field "Estimate=$ESTIMATE"
