name: Add maintenance issue to Project

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    if: github.event.label.name == '保守運用'
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: check gh version
        run: gh --version

      - name: Add issue to GitHub Project and set Estimate
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_PAT }}
          PROJECT_NUMBER: ${{ secrets.PROJECT_NUM }}
          OWNER: ${{ secrets.OWNER_ID }}
          ESTIMATE: 1
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          PROJECT_ID=$(
            gh project view $PROJECT_NUMBER \
            --format json \
            --jq '.id'
          )
          echo "Adding issue $ISSUE_URL to project $PROJECT_ID"
